### ISSUE TITLE
Waiypointのインデックス

### ISSUE THREAD

**Issue by SRJRT** [rohme/Bokka#1]
いつもお世話になっております。
EFの件ではお世話になりありがとうございました。
さて、今回はBokkaなのですが、どうやらまたインデックスが変わっているようで、
COUwaypoint前で止まってしまう現象が起きています。

確認宜しくお願い致します。

**Comment by rohme** [comment]
最近インしていなかったので気づいていませんでした。
Ver0.0.4で修正しました。
